### ISSUE TITLE
Shuttle Diplomacy

### ISSUE THREAD

**Issue by MillerNCHS** [mindreader/twilight-struggle-counter#13]
I love your card counter, but Shuttle Diplomacy has always been a problem. It doesn't really get discarded or removed when it is evented, but those are the only options in your card counter. It's not a major issue, but if you ever look to make some updates, this would be a great one. Thanks for the great website!

**Comment by mindreader** [comment]
I purposely punted that originally but I know the changes I would have to make to make that work. A normally invisible "on board" section that eventing would place it into, with only a discard icon.

I haven't played in a few years though so I would not make the change unless I'm sure it impacts nothing else, and that I'm sure there are no other play on board cards.

**Comment by mindreader** [comment]
I changed the code to make shuttle diplomacy work better. Now there is a flag icon next to it indicating that you can place it in front of the us. It now has a box for that that only appears when the card is in that location. From that location you can discard it.

**Comment by MillerNCHS** [comment]
Appreciate you doing that! I know it took a bit of work to do so.
