### ISSUE TITLE
Card Counter

### ISSUE THREAD

**Issue by BobbyRobertsTS** [mindreader/twilight-struggle-counter#3]
Hi David,

I use your card counter for TS and it's great! However, one thing that would be really useful, if it's not too much hassle to add, would be if you listed the number of cards that are in the deck for each category: US, neutral, USSR.

You currently have the number of cards in the hand section in parenthesis, and also in the discarded and removed sections, but not in the deck section.

Anyone... just a thought.

Much obliged,

Bobby
(TS enthusiast)

**Comment by mindreader** [comment]
Just as an FYI to others, I intend to do this next time I dip into the code.

**Comment by BobbyRobertsTS** [comment]
Great! Have you dipped into the code yet?

**Comment by mindreader** [comment]
Sorry, it just isn't a super high priority. I will eventually get to it, but it could be awhile.

**Comment by BobbyRobertsTS** [comment]
You're obviously living life at DEFCON 5!.....

Cheers.

**Comment by mindreader** [comment]
Better late than never. I had some spare time and added this feature.
